TieuLuan/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TieuLuan.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }

    }
}

TieuLuan/Models/ErrorViewModel.cs
using System;

namespace TieuLuan.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TieuLuan/Models/Laptop.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TieuLuan.Models
{
    public class Laptop
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Color { get; set; }
        [Required]
        public string Manufacturer { get; set; }
        [Required]
        public string CPU { get; set; }
        [Required]
        [Range(8, int.MaxValue, ErrorMessage = "RAM phải lớn hơn 7")]
        public int RAM { get; set; }
        [Required]
        [Range(128, int.MaxValue, ErrorMessage = "Dung lượng phải lớn hơn 127")]
        public int Storage { get; set; }
    }
}

TieuLuan/Models/Phone.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TieuLuan.Models
{
    public class Phone
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Color { get; set; }
        [Required]
        public string Manufacturer { get; set; }
        [Required]
        [Range(128, int.MaxValue, ErrorMessage = "Dung lượng phải lớn hơn 127")]
        public int Storage { get; set; }

    }
}

TieuLuan/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TieuLuan.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TieuLuan/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TieuLuan.Models;

namespace TieuLuan.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TieuLuan/Controllers/LaptopController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TieuLuan.Data;
using TieuLuan.Models;

namespace TieuLuan.Controllers
{
    public class LaptopController : Controller
    {
        private readonly ApplicationDbContext _db;

        public LaptopController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Laptop> List = _db.Laptop;
            return View(List);
        }


        public IActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Laptop lap)
        {
            if (ModelState.IsValid)
            {
                _db.Laptop.Add(lap);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lap);
            
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var lap = _db.Laptop.Find(id);
            if (lap == null)
            {
                return NotFound();
            }
            return View(lap);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Laptop lap)
        {
            if (ModelState.IsValid)
            {
                _db.Laptop.Update(lap);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lap);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var lap = _db.Laptop.Find(id);
            if (lap == null)
            {
                return NotFound();
            }
            return View(lap);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var lap = _db.Laptop.Find(id);
            if (lap == null)
            {
                return NotFound();
                
            }
            _db.Laptop.Remove(lap);
            _db.SaveChanges();
            return RedirectToAction("Index");


        }
    }
}

TieuLuan/Controllers/PhoneController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TieuLuan.Data;
using TieuLuan.Models;

namespace TieuLuan.Controllers
{
    public class PhoneController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PhoneController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Phone> List = _db.Phone;
            return View(List);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Phone ph)
        {
            if (ModelState.IsValid)
            {
                _db.Phone.Add(ph);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ph);

        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var lap = _db.Phone.Find(id);
            if (lap == null)
            {
                return NotFound();
            }
            return View(lap);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Phone ph)
        {
            if (ModelState.IsValid)
            {
                _db.Phone.Update(ph);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ph);

        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var lap = _db.Phone.Find(id);
            if (lap == null)
            {
                return NotFound();
            }
            return View(lap);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var ph = _db.Phone.Find(id);
            if (ph == null)
            {
                return NotFound();

            }
            _db.Phone.Remove(ph);
            _db.SaveChanges();
            return RedirectToAction("Index");


        }
    }
}

TieuLuan/Views/Category/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

TieuLuan/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center ">
    <h2 class="display-4">Tiểu Luận</h2>
    <h2> Chuyên đề Công nghệ phần mềm</h2>
</div>

TieuLuan/Views/Laptop/Create.cshtml
@model TieuLuan.Models.Laptop

<form method="post" asp-action="Create">
    <div class="border p-3" >
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class=" form-group row">
            <h2 class="text-info pl-3">Add Laptop</h2>
        </div> 
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Color"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Color" class="form-control" />
                        <span asp-validation-for="Color" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Manufacturer"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Manufacturer" class="form-control" />
                        <span asp-validation-for="Manufacturer" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CPU"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CPU" class="form-control" />
                        <span asp-validation-for="CPU" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RAM"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RAM" class="form-control" />
                        <span asp-validation-for="RAM" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Storage"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Storage" class="form-control" />
                        <span asp-validation-for="Storage" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-secondary w-100">Back</a>
                        </div>
                    </div>
                    
                </div>
                



            </div>
        </div>
    </div>    
</form>

@section Scripts{
    
    @{ <partial name="_ValidationScriptsPartial"/> }

}

TieuLuan/Views/Laptop/Delete.cshtml
@model TieuLuan.Models.Laptop

<form method="post"  asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class=" form-group row">
            <h2 class="text-info pl-3">Delete Laptop</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                        
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Color"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Color" disabled class="form-control" />
                        
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Manufacturer"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Manufacturer" disabled class="form-control" />

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CPU"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CPU" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RAM"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RAM" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Storage"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Storage" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-secondary w-100">Back</a>
                        </div>
                    </div>

                </div>




            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

TieuLuan/Views/Laptop/Edit.cshtml
@model TieuLuan.Models.Laptop

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class=" form-group row">
            <h2 class="text-info pl-3">Edit Laptop</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Color"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Color" class="form-control" />
                        <span asp-validation-for="Color" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Manufacturer"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Manufacturer" class="form-control" />
                        <span asp-validation-for="Manufacturer" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CPU"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CPU" class="form-control" />
                        <span asp-validation-for="CPU" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RAM"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RAM" class="form-control" />
                        <span asp-validation-for="RAM" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Storage"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Storage" class="form-control" />
                        <span asp-validation-for="Storage" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-secondary w-100">Back</a>
                        </div>
                    </div>

                </div>




            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

TieuLuan/Views/Laptop/Index.cshtml
@model IEnumerable<TieuLuan.Models.Laptop>

<div class=" container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-black-50">Laptop List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Laptop" asp-action="Create" class="btn btn-primary">Create New Laptop</a>
            
        </div>

    </div>

    <br /> <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Laptop </th>
                    <th>Color</th>
                    <th>Manufacturer</th>
                    <th>CPU</th>
                    <th>RAM</th>
                    <th>Storage</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var lap in Model)
                {
                <tr>
                    <td>@lap.Name</td>
                    <td>@lap.Color</td>
                    <td>@lap.Manufacturer</td>
                    <td>@lap.CPU</td>
                    <td>@lap.RAM</td>
                    <td>@lap.Storage</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Laptop" asp-route-Id="@lap.Id" asp-action="Edit" class="btn btn-primary">Edit</a>
                            <a asp-controller="Laptop" asp-route-Id="@lap.Id" asp-action="Delete" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
                }



            </tbody>
        </table>
    }
    else { 
        <p>No Laptop </p>
    }


</div>

TieuLuan/Views/Phone/Create.cshtml
@model TieuLuan.Models.Phone

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class=" form-group row">
            <h2 class="text-info pl-3">Add Phone</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Color"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Color" class="form-control" />
                        <span asp-validation-for="Color" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Manufacturer"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Manufacturer" class="form-control" />
                        <span asp-validation-for="Manufacturer" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Storage"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Storage" class="form-control" />
                        <span asp-validation-for="Storage" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-secondary w-100">Back</a>
                        </div>
                    </div>

                </div>




            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

TieuLuan/Views/Phone/Delete.cshtml
@model TieuLuan.Models.Phone

<form method="post" asp-action="DeletePost" >
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class=" form-group row">
            <h2 class="text-info pl-3">Delete Phone</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                        
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Color"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Color" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Manufacturer"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Manufacturer" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Storage"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Storage" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-secondary w-100">Back</a>
                        </div>
                    </div>

                </div>




            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

TieuLuan/Views/Phone/Index.cshtml
@model IEnumerable<TieuLuan.Models.Phone>

<div class=" container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-black-50">Phone List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Phone" asp-action="Create" class="btn btn-primary">Create New Phone</a>
        </div>

    </div>

    <br /> <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Phone Name
                    </th>
                    <th>
                        Color
                    </th>
                    <th>
                        Manufacturer
                    </th>
                    <th>
                        Storage
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var lap in Model)
                {
                <tr>
                    <td>@lap.Name</td>
                    <td>@lap.Color</td>
                    <td>@lap.Manufacturer</td>
                    <td>@lap.Storage</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Phone" asp-route-Id="@lap.Id" asp-action="Edit" class="btn btn-primary">Edit</a>
                            <a asp-controller="Phone" asp-route-Id="@lap.Id" asp-action="Delete" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
                }



            </tbody>
        </table>
    }
    else
    {
        <p>No Phone exists </p>
    }


</div>

TieuLuan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TieuLuan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tiểu luận</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Phone" asp-action="Index">Phone</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laptop" asp-action="Index">Laptop</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TieuLuan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>